# Generated by Django 2.0.6 on 2018-06-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('block_users', models.ManyToManyField(related_name='_bloguser_block_users_+', to='bloguser.BlogUser')),
                ('friends', models.ManyToManyField(related_name='_bloguser_friends_+', to='bloguser.BlogUser')),
            ],
        ),
    ]
