# Generated by Django 2.0.6 on 2018-06-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=True, related_name='my_address', to='bloguser.BlogUser')),
                ('phone_number', models.OneToOneField(on_delete=True, related_name='my_phone_number', to='bloguser.BlogUser')),
            ],
        ),
    ]
