# Generated by Django 2.0.6 on 2018-06-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_address', to='bloguser.BlogUser'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_phone_number', to='bloguser.BlogUser'),
        ),
    ]
